### ISSUE TITLE
Markdown of readme has gone skewy

### ISSUE THREAD

**Issue by iteles** [ladiesofcode/team#4]
Just requires some spaces between the `#` and the words in the titles

<img width="714" alt="screen shot 2017-10-26 at 10 21 56" src="https://user-images.githubusercontent.com/4185328/32045307-d73202e6-ba37-11e7-92a8-804e8837fda5.png">

**Comment by SuzeShardlow** [comment]
I've had a try :)

**Comment by iteles** [comment]
🎉 Thanks!
