### ISSUE TITLE
Update London team

### ISSUE THREAD

**Issue by iteles** [ladiesofcode/team#5]
The London team is out of date in this `readme` and needs to be updated as per https://github.com/ladiesofcode/london

**Comment by SuzeShardlow** [comment]
I have had a go at doing this :)

**Comment by iteles** [comment]
Thanks @SuzeShardlow !

**Comment by iteles** [comment]
@SuzeShardlow Are you up for another round? 😉

**Comment by SuzeShardlow** [comment]
@iteles I have done this - #7 refers.  I was able to make the changes without needing to create a pull request :)
